### ISSUE TITLE
[xdgurl2]: reverse ok/cancel buttons

### ISSUE THREAD

**Issue by star-buck** [ocs-url/ocs-url#21]
in all kde, qt, windows, android, etc. ok/cancel buttons are reversed compared to this:
![screenshot_20161018_162257](https://cloud.githubusercontent.com/assets/840070/19481866/a4195fb6-954f-11e6-8a0a-048286b71a0b.png)

**Comment by akiraohgaki** [comment]
That buttons are orderd by Qt/QML dialog, and I think that is correct order.

**Comment by akiraohgaki** [comment]
Done.
so button order is [OK] [Cancel].
