### ISSUE TITLE
Translations ?

### ISSUE THREAD

**Issue by tarakbumba** [ocs-url/ocs-url#32]
I see that xdgurl isn't localized. All text displayed in English. Are there any plans to add localization support?

**Comment by akiraohgaki** [comment]
In program side, we make the messages translatable. maybe it's version 3.0.

**Comment by akiraohgaki** [comment]
OK, labels and messages are translatable.
And continue localization support https://github.com/ocs-url/ocs-url/wiki/Internationalization
