### ISSUE TITLE
Ubuntu 14.04

### ISSUE THREAD

**Issue by CarlosUrteaga** [ocs-url/ocs-url#34]
S.O. Ubuntu 14.04 LTS
error while trying to install, Dependency  is not satisfiable libqt5svg5 (>=5.3.0)
actual libqt5svg5_5.2.1-1

**Comment by akiraohgaki** [comment]
xdgurl depend QtQuick dialogs, it since Qt 5.3.
So I recommend Ubuntu users to upgrade system to Ubuntu 16.04 LTS.

**Comment by CarlosUrteaga** [comment]
great just update your requirements and wWaow, you are an amazing noob developer who thinks everyone will upgrade to have a fancy interface. I was expecting that you will release an old version.  thanks

**Comment by star-buck** [comment]
@akiraohgaki : any way we can make the minimal window interaction necessary for xdgurl based on a more widely available Qt version or toolkit?

**Comment by akiraohgaki** [comment]
@CarlosUrteaga 
We will make support widely in xdgurl 3.x, but Ubuntu 16.04 required for now.

**Comment by akiraohgaki** [comment]
@star-buck 
Yes, I have a plan to make xdgurl widely available, like xdgurl 1.x.
Maybe xdgurl version 2.1 (or 3.x series).

**Comment by star-buck** [comment]
2.1 would do fine.

**Comment by akiraohgaki** [comment]
OK, now, ocs-url (xdgurl) has supported old Qt 5.2, so available on Ubuntu 14.04.
And will release it as ocs-url 3.0 in next.
