### ISSUE TITLE
rename xdgurl 3.0 to ocs-url ?

### ISSUE THREAD

**Issue by star-buck** [ocs-url/ocs-url#35]
For consistency:
ocs://

**Comment by akiraohgaki** [comment]
Sounds good!

So we change below things:

Github:
* organization name
* repository name

Links:
* wiki, docs, license file
* linux-apps product page

Program:
* package name
* binary name
* icon name and design
* url scheme

**Comment by akiraohgaki** [comment]
We should support both ocs:// and xdg:// in program side, and release the new version before we switch xdg:// to ocs:// in ocs service side.

So can we start the rename about xdgurl project, from now?

**Comment by star-buck** [comment]
Yes.

**Comment by akiraohgaki** [comment]
Report.

Renamed github organization:
https://github.com/ocs-url

Renamed github repositories:
https://github.com/ocs-url/ocs-url
https://github.com/ocs-url/ocs-url-icon

Wiki, Help, Product page:
https://github.com/ocs-url/ocs-url/wiki
https://ocs-url.github.io/ocs-url/opendesktoporg-help.html
https://www.linux-apps.com/p/1136805/

A links to the help page inside ocs-webserver also changed. (so waiting for next deploy)

New icon:
https://github.com/ocs-url/ocs-url-icon/blob/master/ocs-url.svg

**Comment by star-buck** [comment]
looking nice!

**Comment by akiraohgaki** [comment]
Report.

* Support ocs:// scheme
* Still support xdg:// scheme for backward compatibility
* Renamed binary name
* Renamed package name
* Replaced icon and .desktop
* Changed links in config, package, license files

So close this issue, and continue to https://github.com/ocs-url/ocs-url/issues/34
