### ISSUE TITLE
Update gallery on product page and YouTube video

### ISSUE THREAD

**Issue by akiraohgaki** [ocs-url/ocs-url#36]
When new ocs-url program comming.

**Comment by star-buck** [comment]
Why not use this:
https://github.com/ocs-url/ocs-url/blob/gh-pages/opendesktoporg-help.html

Is it served by github.com?

**Comment by akiraohgaki** [comment]
@star-buck 
We use that, of course.
I mean about gallery in product page at linux-apps and video at YouTube.
Because name and icon changed (and will change dialog in next release).

**Comment by akiraohgaki** [comment]
Done.
So name, icon, url, pictures, video, completelly replaced from xdgurl to ocs-url.
