### ISSUE TITLE
change description on product page

### ISSUE THREAD

**Issue by star-buck** [ocs-url/ocs-url#38]
current:
"An install helper program for desktop stuff."

new:
"An install helper program for items served over OpenCollaborationServices (OCS) API.

**Comment by akiraohgaki** [comment]
ocs-url(xdgurl) not used OCS API.

**Comment by akiraohgaki** [comment]
Do you like this?

"An install helper program for items served on OpenCollaborationServices (OCS)."

**Comment by star-buck** [comment]
Yes, sure.

**Comment by akiraohgaki** [comment]
OK, updated.
description in program and package also updated.
